LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY provjera_bita IS
PORT(
	X: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
	Y: OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
);
END provjera_bita;

ARCHITECTURE arch_provjera_bita OF provjera_bita IS
BEGIN
	Y <= X WHEN ((X(0)XOR X(1) XOR X(2) XOR X(3)) = '0') ELSE "ZZZZ";
END ARCHITECTURE;
